### PR TITLE
Complete question managing

### PR DESCRIPTION
**Pull request by JacksonTai**
This covers editing and deleting question in question page and layout.

### CODE REVIEW

**Review by hochangyong — APPROVED** [review]

**Comment by hochangyong** [comment]
do we need to do this edit and delete for comment and answer ? We got proposed in our hierarchy chart

**Comment by JacksonTai** [comment]
> do we need to do this edit and delete for comment and answer ? We got proposed in our hierarchy chart

Yes, I'm separating it into another branch

**Comment by hochangyong** [comment]
thanks a lot jackson, me and e heng will help you done your part of unit testing, almost finish alrd

**Comment by JacksonTai** [comment]
> thanks a lot jackson, me and e heng will help you done your part of unit testing, almost finish alrd

Ok, so far still left edit answer, edit comment, and delete comment. If there's no any issue or silly mistake that keep me stuck, I might be able to finish it by tmr morning

**Review by EHeng17 — APPROVED** [review]

**Pull request merged**
