### PR TITLE
Done manage qa admin

### PR DESCRIPTION
**Pull request by EHeng17**

### CODE REVIEW

**Review by hochangyong — APPROVED** [review]

**Review by JacksonTai — DISMISSED** [review]
Just a small advice, maybe next time the CSS code can be ordered based on the HTML code from top to bottom, so it's easier to find stuff.

**Comment by EHeng17** [comment]
The button didn't disappear
image
I made it at the bottom right of the panel if it is in mobile size. 2 big buttons feel weird

**Review by JacksonTai — APPROVED** [review]

**Comment by JacksonTai** [comment]
> The button didn't disappear image I made it at the bottom right of the panel if it is in mobile size. 2 big buttons feel weird

Got it, sorry for overlooking the button

**Comment by JacksonTai** [comment]
@jyyyyylim Is everything ok?

**Pull request merged**
