### PR TITLE
Fix/user leaderboard

### PR DESCRIPTION
**Pull request by hochangyong**
Done with everything include responsive design and already keep with the latest master branch, please have a look

### CODE REVIEW

**Comment by JacksonTai** [comment]
I tried to hard refresh the browser and check if I pull the latest commit of this branch, but the layout still break. Are you guys seeing the same thing?
image

**Comment by hochangyong** [comment]
> I tried to hard refresh the browser and check if I pull the latest commit of this branch, but the layout still break. Are you guys seeing the same thing? image

image
it suppose to be like this

**Comment by hochangyong** [comment]
it is the resolution problem ?

**Comment by JacksonTai** [comment]
> is it the resolution problem ?

Can you inspect your browser and check it on different devices?
image

**Comment by hochangyong** [comment]
ya same with you. The all ranking at the bottom section there is hard to do, because when minimize the chrome until the smallest, it shown the result as i reply above, so i think should be fine alrd

**Comment by hochangyong** [comment]
the layout keep breaking when i minimize, i use a lot of time to solve it, then i got the result as the pic i reply above. i didnt realize it still have the lower dimension

**Comment by JacksonTai** [comment]
Ok, at least you tried your best, I will help you to fix it once we finish the backend

**Review by JacksonTai — APPROVED** [review]
Partially done for temporarily working responsive design, will get back to this once backend is finished.

**Comment by JacksonTai** [comment]
> btw, is the user dashboard got problem ?

I didn't see any severe overflow error happen, but the layout became unorganized and not totally responsive on some mobile devices. We will get back to this as well, since it's not affecting us from proceeding with the backend.

**Comment by hochangyong** [comment]
> > btw, is the user dashboard got problem ?
> 
> I didn't see any severe overflow error happen, but the layout became unorganized and not totally responsive on some mobile devices. We will get back to this as well, since it's not affecting us from proceeding with the backend.

alright, i will look back on my local, i try to solve if i can

**Comment by JacksonTai** [comment]
Can you proceed with some other part, probably the backend? I can help you to handle this. Maybe you can review my code and see how to solve it?

**Review by EHeng17 — APPROVED** [review]

**Review by jyyyyylim — APPROVED** [review]

**Pull request merged**
