### PR TITLE
Fix backend for admin dashboard

### PR DESCRIPTION
**Pull request by JacksonTai**

### CODE REVIEW

**Comment by hochangyong** [comment]
jackson, i got the error at the page navigation and filter in this pr
did others faced the same issue with me ?

**Comment by JacksonTai** [comment]
> jackson, i got the error at the page navigation and filter in this pr did others faced the same issue with me ?

My bad, I haven't kept this branch up to date.

**Comment by hochangyong** [comment]
> > jackson, i got the error at the page navigation and filter in this pr did others faced the same issue with me ?
> 
> My bad, I haven't kept this branch up to date.

ohoh, it's okay jackson

**Comment by JacksonTai** [comment]
Please have a look at it again.

**Comment by hochangyong** [comment]
okay

**Review by hochangyong — APPROVED** [review]

**Review by EHeng17 — APPROVED** [review]

**Pull request merged**
