### PR TITLE
Complete backend for question page.

### PR DESCRIPTION
**Pull request by JacksonTai**
**Completed:**
- Reading of `question info`. 
- Adding and viewing of `answer`.
- Adding and viewing of `comment`.
- Adding, viewing and removing of `bookmark`.
- Voting system.
 
**Pending:** _(Update: Completed pending tasks on 23/3/2022)_
- answer post date and timestamp _(I was thinking if we can remove this in our design, then we can skip this)_
- accept and remove accept `answer`.

> I encounter some issues with the voting system, which unexpectedly takes me some more time to finish. So I was thinking if I can PR and ask you guys to help me check what I've got by now meanwhile I will be continuing with the rest of the pending tasks _(Update: Completed pending tasks on 23/3/2022)_. Also, do let me know your opinion on the answer post date and timestamp.

**Note:**
I have changed the SQL file, please import it again.

### CODE REVIEW

**Comment by JacksonTai** [comment]
In case you guys don't want to create all data again, do reach out for a database with dummy data.

**Comment by jyyyyylim** [comment]
can pr first, will surely contribute here if only i could get querying for my part to work.
if you dont mind may i have the dummy data?

**Review by jyyyyylim — APPROVED** [review]

**Comment by hochangyong** [comment]
Jackson, i cannot view my bookmark, but i can add and remove bookmark

**Comment by hochangyong** [comment]
image
and when i answering a question, it cannot be posted, my page got this error, is it only me got this problem ?

**Comment by jyyyyylim** [comment]
>dest unreachable on comment post
not sure ab that, no action on my end, but comment post isnt reflected in db.

>bookmarking
bookmarked post isnt reflected in visitation in that the button isnt highlighted on revisiting a bookmarked post. this may not be intended

**Pull request closed without merging**
