### PR TITLE
Manage user search

### PR DESCRIPTION
**Pull request by EHeng17**
**Done with search**
Please have a look at let me know if there are any problems

If u type in a random name like 'dasdasdasd' into search bar, IF U KNOW that there wont be an output, u have to scroll a little down to activate the dynamic loading, as it works if it detects a scroll.

### CODE REVIEW

**Comment by hochangyong** [comment]
why all the users from user dashboard disappear? it won't show the user at user dashboard
is it only me got this problem ?

**Comment by EHeng17** [comment]
Chang Yong, check again

**Review by JacksonTai — APPROVED** [review]
Nice work E heng!

**Comment by hochangyong** [comment]
everything looks good now, thank you E Heng

**Review by hochangyong — APPROVED** [review]

**Review by jyyyyylim — APPROVED** [review]

**Pull request merged**
