### PR TITLE
Done leaderboard backend

### PR DESCRIPTION
**Pull request by EHeng17**
Added 2 classes
1 for Top Three (Rank 1-3)
1 for Top Ten (Rank 4-10)

Used array number for rank 1-3, as not all has the same html code
Used for loop to loop the ranks from 4 to 10 as all use the same layout.

Let me know what can be changed

### CODE REVIEW

**Comment by hochangyong** [comment]
sorry for telling, now i only notice that the box of second place is smaller than third place ?

**Comment by EHeng17** [comment]
> why the box of second place is smaller than third place ?

I think its because of the length of the names, let me make a fixed size

**Comment by EHeng17** [comment]
I made the longer words disappear instead of putting it on the second line, have a look at it. If u dont like the overflow hidden, I can try to break the long words

**Comment by hochangyong** [comment]
maybe smaller the font-size and make it word wrap, i think will better

**Comment by hochangyong** [comment]
image
image
E Heng, i think the arrangement got messed up

**Review by JacksonTai — APPROVED** [review]

**Review by hochangyong — APPROVED** [review]

**Pull request merged**
