### PR TITLE
completed qn and verif dashboard

### PR DESCRIPTION
**Pull request by jyyyyylim**
also:
>componentized right sidebar in home as trending-sidebar
>updated head.php to correspond 

though unlikely, do check for breakages in other pages, thanks

### CODE REVIEW

**Comment by JacksonTai** [comment]
Am I the only one who sees these issues? 
image 15

image 14

image 16

**Comment by jyyyyylim** [comment]
image
works fine on my end, even on chrome

**Comment by EHeng17** [comment]
> 

image
image
My verification page is a little different compared to Jackson's
I also have the problems that was mentioned by Jackson.

**Comment by JacksonTai** [comment]
> image works fine on my end, even on chrome

Did you try to shrink your browser?

**Comment by hochangyong** [comment]
i have the same problem with e heng and jackson also

**Comment by jyyyyylim** [comment]
does this fix it?

**Comment by hochangyong** [comment]
> does this fix it?

no dude, the responsive still the same

**Comment by jyyyyylim** [comment]
image
this is it when compressed across width. does it need to extend fully at this state?

**Comment by jyyyyylim** [comment]
changyong, can ss? tq

**Comment by hochangyong** [comment]
> changyong, can ss? tq

i mean the verif dashboard

**Comment by hochangyong** [comment]
it is still the same as e heng mentioned jn

**Comment by hochangyong** [comment]
> image this is it when compressed across width. does it need to extend fully at this state?

i think this one is still not the dimensions of iphone XR, you try to open the inspect and see the iphone XR size

**Comment by jyyyyylim** [comment]
image
should be ok?

**Comment by jyyyyylim** [comment]
hold on, still trying to rectify the sidebar overlap issue

**Pull request closed without merging**
