### PR TITLE
Admin dashboard

### PR DESCRIPTION
**Pull request by EHeng17**
Please have a look at the admin dashboard. If it is to your liking, we can merge it, then I'll start putting the sidenav to the leaderboard branch

### CODE REVIEW

**Review by jyyyyylim — APPROVED** [review]

**Comment by JacksonTai** [comment]
image
image
Is this the result?

**Review by hochangyong — APPROVED** [review]

**Comment by EHeng17** [comment]
Wait no, that isn't how it is supposed to look like. Let me show it to you

**Comment by EHeng17** [comment]
image
image
This is how it looks like for me

**Comment by EHeng17** [comment]
Maybe try Ctrl+F5 to refresh? I have cloned and pulled it again, and it looks the same to me. No problems like the one you have shown

**Comment by hochangyong** [comment]
yup, i can see the result same as e heng

**Review by JacksonTai — APPROVED** [review]

**Pull request merged**
