### PR TITLE
Done - Ask question backend

### PR DESCRIPTION
**Pull request by EHeng17**
I'm done with the backend of ask question

Included:
Check for empty input, 
Pop up alert once question is submitted.

### CODE REVIEW

**Comment by JacksonTai** [comment]
We need validation for title and content length as well. Speaking of field length, how long do you guys think we should put for tag?

**Comment by EHeng17** [comment]
> 

I have placed a maxlength of 100 in the html tag for the title. for content, should I put maxlength of 16,777,215 in the html tag for the content?

**Comment by JacksonTai** [comment]
> > 
> 
> I have placed a maxlength of 100 in the html tag for the title. for content, should I put maxlength of 16,777,215 in the html tag for the content?

My bad for overlooking it on the HTML element. Do you think it will be better if we use VARCHAR of 10000 characters? Cause I'm not sure if there will ever be a question that is 16777215 long. If not, we can just put 16777215 as max in the HTML tag for content.

**Comment by EHeng17** [comment]
> > > 
> > 
> > 
> > I have placed a maxlength of 100 in the html tag for the title. for content, should I put maxlength of 16,777,215 in the html tag for the content?
> 
> My bad for overlooking it on the HTML element. Do you think it will be better if we use VARCHAR of 10000 characters? Cause I'm not sure if there will ever be a question that is 16777215 long. If not, we can just put 16777215 as max in the HTML tag for content.

I agree with you. Varchar should be fine. From what I read, Varchar has a maximum size is 65k ish characters, and it is more efficient as u can index, and it uses less space.

Let me know your final thoughts, I will change it.

**Comment by JacksonTai** [comment]
> 

Ok, I think we can go for it, the reasons you've mentioned is actually the same as what I thought of.

**Comment by EHeng17** [comment]
> > 
> 
> Ok, I think we can go for it, the reasons you've mentioned is actually the same as what I thought of.

Okay, I will do the necessary changes. How many characters do u prefer? 10k, or the maximum, 65k?

**Comment by JacksonTai** [comment]
> > > 
> > 
> > 
> > Ok, I think we can go for it, the reasons you've mentioned is actually the same as what I thought of.
> 
> Okay, I will do the necessary changes. How many characters do u prefer? 10k, or the maximum, 65k?

I think both are fine since it's not the crucial part, and we can change it later on as things go on. Let's go with 10k for now.

**Review by JacksonTai — APPROVED** [review]
Nice work, I never heard of sweetAlert2, but I found it very handy to use for a simple pop out alert message.

**Comment by EHeng17** [comment]
> > > > 
> > > 
> > > 
> > > Ok, I think we can go for it, the reasons you've mentioned is actually the same as what I thought of.
> > 
> > 
> > Okay, I will do the necessary changes. How many characters do u prefer? 10k, or the maximum, 65k?
> 
> I think both are fine since it's not the crucial part, and we can change it later on as things go on. Let's go with 10k for now.

Okay no issues, I will change the content from mediumtext to varchar, and put a maxlength of 10k in the html tag for content

**Review by jyyyyylim — APPROVED** [review]

**Pull request merged**
